server:
  port: 8084

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/tastytrade
    username: tastytrade
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  data:
    jpa:
      repositories:
        enabled: true

tastytrade:
  app:
    jwtSecret: tastytradeSecretKey123456789abcdefghijklmnopqrstuvwxyz
    jwtExpirationMs: 86400000
    jwtRefreshExpirationMs: 120000000

logging:
  level:
    com.tastytrade: DEBUG
    org.springframework.security: DEBUG