services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    environment:
      POSTGRES_DB: tastytrade
      POSTGRES_USER: tastytrade
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=en_US.UTF-8 --lc-ctype=en_US.UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
      - ./infrastructure/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: ["postgres", "-c", "shared_preload_libraries=timescaledb"]

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: tastytrade
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  api-gateway:
    build: ./services/api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
    depends_on:
      - timescaledb
      - redis
      - rabbitmq

  tastytrade-integration:
    build: ./services/tastytrade-integration
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=local

  market-data-service:
    build: ./services/market-data-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=local
    depends_on:
      - timescaledb
      - redis
      - rabbitmq

  portfolio-service:
    build: ./services/portfolio-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=local
    depends_on:
      - timescaledb
      - redis
      - rabbitmq

volumes:
  timescaledb_data:
  redis_data:
  rabbitmq_data: