version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: tastytrade
      POSTGRES_USER: tastytrade
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api-gateway:
    build: ./services/api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
    depends_on:
      - postgres
      - redis

  tastytrade-integration:
    build: ./services/tastytrade-integration
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=local

  market-data-service:
    build: ./services/market-data-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=local
    depends_on:
      - postgres
      - redis

  portfolio-service:
    build: ./services/portfolio-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=local
    depends_on:
      - postgres

volumes:
  postgres_data: