package com.tastytrade.delta.model;

public enum AlertType {
    DELTA_THRESHOLD_BREACH,
    GAMMA_THRESHOLD_BREACH,
    THETA_THRESHOLD_BREACH,
    VEGA_THRESHOLD_BREACH,
    PORTFOLIO_DELTA_BREACH,
    POSITION_SIZE_LIMIT,
    VOLATILITY_SPIKE,
    UNUSUAL_VOLUME,
    PRICE_MOVEMENT,
    EXPIRATION_WARNING,
    MARGIN_CALL,
    SYSTEM_ERROR
}