server:
  port: 8082

spring:
  application:
    name: market-data-service
  datasource:
    url: jdbc:postgresql://localhost:5432/tastytrade
    username: tastytrade
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
      database: 2
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 50
          max-idle: 20
          min-idle: 5

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.tastytrade: DEBUG
    org.springframework.messaging: DEBUG
    reactor.netty: INFO